### ISSUE TITLE
Connection refused

### ISSUE THREAD

**Issue by goodgarcia21** [Eiim/Chokistream#12]
![image](https://user-images.githubusercontent.com/104873313/210183067-6f06d4d1-714d-48e7-a94d-43f7d3303227.png)
im tried with HZmod and NTR boost but nothing, i've an old 3ds and my pc and Nintendo both in the same wifi receptor so idk what can be to fix the error :(

**Comment by Eiim** [comment]
Can I see the settings? And can you ping the 3DS from the computer?

**Comment by goodgarcia21** [comment]
![image](https://user-images.githubusercontent.com/104873313/210184748-d8cf4c35-d971-4692-95e3-0f02a01fc1c2.png)
i have the default setting if you mean chokistream program. Yes i can ping the 3ds with the computer, i use ftp to transfer some cias too so idk what can be. i just read some about the port of my console is 5000 (i tried to change on the program but nothing) and read too something about the DNS..

**Comment by Eiim** [comment]
Hm. Yeah, if HzMod/NTR is running and the DS is pingable from that same IP, then there shouldn't be any problem. DNS shouldn't be an issue since you're using the IP directly. There's a slim chance that there's a firewall on the network you're using but if you can FTP to it that also seems unlikely.

Possibly it's an issue with NTR or HzMod not starting properly. HzMod uses the notification LED to indicate that it's started up properly; do you see it turn a blue/green?

Also, perhaps try Snickerstream to see if it's able to connect. If it can, then there's something to dig deeper on the Chokistream side.

**Comment by goodgarcia21** [comment]
sometimes the led turn on blue but after a seconds the led just turn off. (a little ask the led need to stay ON in every moment?)
i tried on snickerstream too and i just get could not connect too (N) 3ds message.
maybe can be the firewall but i don't know how that works properly if can help with that.
or what can be :(

**Comment by goodgarcia21** [comment]
i can rec you a video if is possible

**Comment by Eiim** [comment]
I'm pretty confident this is 3DS-side at this point. The HzMod LED should stay on if you don't do anything with it (if you start other programs it will usually stay blue but sometimes another program will take control. It also flashes red when you press buttons, that's normal). I can suggest trying ChirunoMod, it's diverged enough from HzMod that it's possible it fixed whatever problem you're having. Unfortunately that's outside the range of my expertise though. I'm going to close this issue since it appears to be outside of Chokistream at this point but feel free to keep asking questions here if I can be of any further help.
