### ISSUE TITLE
Unable to send NTR Patch to console

### ISSUE THREAD

**Issue by pedroverri** [Eiim/Chokistream#18]
**Describe the bug**
I'm unable to send the NTR Patch to my system, encountering the error message "java.lang.NullPointerException: Cannot read the array length because 'add' is null". Therefore some games get stuck in a black screen, such as Pokemon Omega Ruby

**Steps taken**
Just downloaded Chokistream, used NTR Selector on my console and started NTR 3.6 as per usual. Everything is connecting fine, but I'm unable to send the NTR Patch. It is working fine on Kit Kat Slim on Windows when I tried, but that is my friend's PC.

**Versions/settings**
 * Chokistream 2023/08/23
 * macOS Ventura 13.5.1
 * NTR 3.6
 * New 3DS
 * Pokemon Omega Ruby

![image](https://github.com/Eiim/Chokistream/assets/17335608/7c074426-b40b-4fe4-8072-d57e5a391b79)

**Additional context**
Not sure if related at all, but I tried HzMod and ChirunoMod and neither show the bottom screen, but NTR does so that's why I stick with it.

**Comment by Eiim** [comment]
NTR patch is known/expected to not work well, but that particular issue is surprising. I haven't tested that code in ages so I'll take another look.

There shouldn't be a problem with the bottom screen and ChirunoMod. Make sure you're on version 0.2.1 of ChirunoMod and that you're requesting both screens in the ChirunoMod settings. If that's still an issue, please open another bug for that.

However, it still probably won't work for Omega Ruby because I believe that game does a WiFi reset when it starts, which is why the NTR patch is required, and there's no equivalent workaround for HzMod or ChirunoMod.

Bottom screen is only supported in the very first release of HzMod, 2017-05-05 (and the December 2017 build but [we don't support that build](../wiki/HzMod-Support-Comparison)). You can find that build [here](https://chainswordcs.com/horizon-by-sono.html). Similarly to ChirunoMod, if you try that, let me know if it doesn't work, but it also won't work with Omega Ruby.

**Comment by pedroverri** [comment]
Thanks for the fast reply! 

I was able to confirm that I'm indeed using version 0.2.1 of ChirunoMod and requesting both screens in the Settings. Setting the screen layout as vertical even displays the windows in the height to have both screen, but the image in the bottom one is just black.

I tried using CuteNTR just for good measure and it's also not sending the NTR Patch over the console. It doesn't throw an error code, but nothing is patched resulting in the same black screen for Omega Ruby. I've been able to somewhat circumvent this by sending the patch using Kit Kat Slim on a Windows PC and then connecting with Chokistream on my Mac and it's been streaming steady and fine!

This is probably a Mac issue if I was to make I guess... Anyway, thank you so much for your work, glad to help in any way I can!

EDIT:
I also made the test in two different New 3DS (just in case) both returned the exact same error when trying to send the NTR Patch

**Comment by Eiim** [comment]
This is definitely an issue, but doing it properly will be non-trivial. I've set it to "Medium Term" in the project right now as there's a workaround for it, but I'm definitely interested in getting this working. Thanks for the detailed report!

**Comment by Eiim** [comment]
@ChainSwordCS took this up yesterday, so we've now released it in v2.0.1! It should work quite similarly to Kit Kat Slim and Snickerstream. There may be some other improvements here for the future but it should be functional now.
