### ISSUE TITLE
Java exception???

### ISSUE THREAD

**Issue by tomasxd12** [Eiim/Chokistream#27]
was trying to run it and well read the title, java 8, i can't find the java 17 download page, is it java  jdk 17?
![bruh](https://github.com/Eiim/Chokistream/assets/134829001/dc2bf247-2f04-4683-8834-85fd694877b1)
![bruh](https://github.com/Eiim/Chokistream/assets/134829001/9113e352-75bc-4fb2-85c5-ca352b5de650)

**Comment by herronjo** [comment]
Yes, it is Java JDK 17 if you're downloading using [Oracle's website](https://www.oracle.com/java/technologies/downloads/#java17)

You can get just the runtime version if you don't want the full JDK from the [Adoptium website](https://adoptium.net/temurin/releases/?package=jre&version=17). Oracle unfortunately does not offer a runtime version of Java 17, and Adoptium is an open source build of Java that does.

Java 8 will not work, since this is built using a newer version of Java than it.

**Comment by tomasxd12** [comment]
oh

**Comment by tomasxd12** [comment]
I see.. But i've got an question: Why is Oracle not offering Java 17 (runtime)? It's kinda rare, honestly. Like they're make Java 8 not outdated, by like for end systems? And Minecraft even stopped support for that java version, right? Only old programs (java) use that.

**Comment by herronjo** [comment]
Yes, even Minecraft has stopped supporting Java 8 and uses the OpenJDK build of the Java 17 runtime. I don't have an answer why Oracle doesn't offer a runtime, especially since the newer runtimes work with older Java programs. Maybe they want you to have the development kit whenever you download Java, I'm not sure.

**Comment by Eiim** [comment]
Not sure why this was re-opened, but I'm closing it. As an aside, I think Minecraft uses the Microsoft OpenJDK builds, which don't have JRE versions, so even that uses a JDK. Quite bizarre that Oracle only has Java 8 for JREs though.
